name: Build and test packages

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build source distribution
        run: |
          python -m pip install build
          python -m build --sdist
      - name: Upload source distribution
        uses: actions/upload-artifact@v4
        with:
          name: sdist-${{ github.sha }}
          path: ./dist/pyisyntax-*.tar.gz
          if-no-files-found: error

  test-sdist:
    name: Test source distribution
    needs: build-sdist
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch source distribution
        uses: actions/download-artifact@v4
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install the package
        run: |
          python -m pip install dist/pyisyntax-*.tar.gz
      - name: Test with pytest
        run: |
          python -m pip install pytest==8.0.0 pytest-mock==3.12.0
          pytest tests/

  build-wheels:
    name: Build ${{ matrix.platform_tag }} wheels
    needs: build-sdist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform_tag: manylinux_x86_64
            os: ubuntu-22.04
          - platform_tag: macosx_x86_64
            os: macos-13
          - platform_tag: macosx_arm64
            os: macos-14
          - platform_tag: win_amd64
            os: windows-2022
    steps:
      - name: Fetch source distribution
        uses: actions/download-artifact@v4
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - run: mv dist/pyisyntax-*.tar.gz pyisyntax.tar.gz
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        with:
          package-dir: pyisyntax.tar.gz
          output-dir: dist
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD: cp310-${{ matrix.platform_tag }}
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.10'
          CIBW_TEST_REQUIRES: pytest==8.0.0 pytest-mock==3.12.0
          CIBW_TEST_COMMAND: pytest {package}/tests
      - name: abi3audit
        run: |
          python -m pip install abi3audit
          python -m abi3audit $(ls ./dist/*.whl) --debug --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform_tag }}-${{ github.sha }}
          path: ./dist/*.whl
          if-no-files-found: error

  merge-artifacts:
    name: Merge build artifacts
    runs-on: ubuntu-latest
    needs:
      - build-sdist
      - build-wheels
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: merged-artifacts-${{ github.sha }}
