name: Build and test packages

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build source distribution
        run: |
          python -m pip install build
          python -m build --sdist
      - name: Upload source distribution
        uses: actions/upload-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: ./dist/pyisyntax-*.tar.gz
          retention-days: 7

  test-sdist:
    name: Test source distribution
    needs: build-sdist
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch source distribution
        uses: actions/download-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install the package
        run: |
          python -m pip install dist/pyisyntax-*.tar.gz
      - name: Test with pytest
        run: |
          python -m pip install pytest==8.0.0 pytest-mock==3.12.0
          pytest tests/

  build-wheels:
    name: Build ${{ matrix.cibw_build }} wheels
    needs: build-sdist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            cibw_archs: x86_64
            cibw_build: "cp3*-manylinux_x86_64"
            compile_target: x86_64
    steps:
      - name: Fetch source distribution
        uses: actions/download-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - run: mv dist/pyisyntax-*.tar.gz pyisyntax.tar.gz
      - name: Build wheels for ${{ matrix.os }} ${{ matrix.cibw_archs }} ${{ matrix.cibw_build }}
        uses: pypa/cibuildwheel@v2.15.0
        with:
          package-dir: pyisyntax.tar.gz
          output-dir: dist
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_SKIP: ${{ matrix.cibw_skip }}
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.10'
          CIBW_TEST_REQUIRES: pytest==8.0.0 pytest-mock==3.12.0
          CIBW_TEST_COMMAND: pytest {package}/tests
      - uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ github.sha }}
          path: ./dist/*.whl
          retention-days: 7
